export const ACTION_TYPES = {
  USER_LOGIN_LOADING: 'USER_LOGIN_LOADING',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',

  USER_SIGNUP_LOADING: 'USER_SIGNUP_LOADING',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAILED: 'USER_SIGNUP_FAILED',
  
  USER_LOGOUT: 'USER_LOGOUT',

  USER_FETCH_PRODUCTS: 'USER_FETCH_PRODUCTS',
  USER_FETCH_PRODUCTS_SUCCESS: 'USER_FETCH_PRODUCTS_SUCCESS',
  USER_FETCH_PRODUCTS_FAILED: 'USER_FETCH_PRODUCTS_FAILED',
};
