export const ACTION_TYPES = {
  USER_LOGIN_LOADING: 'USER_LOGIN_LOADING',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',

  USER_WISHLIST: 'USER_WISHLIST',
  USER_CART: 'USER_CART',




  USER_FETCH_PRODUCTS: 'USER_FETCH_PRODUCTS',
  USER_FETCH_PRODUCTS_SUCCESS: 'USER_FETCH_PRODUCTS_SUCCESS',
  USER_FETCH_PRODUCTS_FAILED: 'USER_FETCH_PRODUCTS_FAILED',
};
